### PR TITLE
Add Topic description into api.yaml

### PR DESCRIPTION
**Pull request by Ielay**
Issue [#308](https://github.com/malinink/easy-tests/issues/308)

### CODE REVIEW

**Comment by Ielay** [comment]
@malinink 
Created a new branch. Done cs fixes. Ready to review.

**Comment by malinink** [comment]
Still there are some cs changes in descriptions

**Comment by Ielay** [comment]
@malinink 
For now I rly did my best

**Comment by malinink** [comment]
A lot of things changed 5cbc011f0cfe3fefcbd2fab46ee171efc4736d07
Topics also modified, take a look please.

**Pull request merged**
