### PR TITLE
Refactor AnswerModelTest and AnswerServiceTest

### PR DESCRIPTION
**Pull request by SakhPrace**
#272 
 - [X] Refactor AnswerModelTest
 - [X] Refactor AnswerServiceTest

### CODE REVIEW

**Comment by SakhPrace** [comment]
@malinink Check my last commit please

**Comment by malinink** [comment]
@SakhPrace looks good!

**Comment by SakhPrace** [comment]
@malinink check this PR please

**Comment by malinink** [comment]
@SakhPrace @AnyaMaz 
Missed testFindAllWithOptions in serviceTest

**Comment by SakhPrace** [comment]
@malinink I see only one method findAll in AnswersService and this method cant get options Options

**Comment by malinink** [comment]
@SakhPrace add method and provide test pls

**Comment by SakhPrace** [comment]
@malinink It's done. Check pls.

**Comment by malinink** [comment]
@SakhPrace 
For future commits: one commit per file pls!

**Comment by malinink** [comment]
@SakhPrace well done!

**Pull request merged**
