### PR TITLE
Refactor SolutionModelTest and SolutionsServiceTest

### PR DESCRIPTION
**Pull request by SvetlanaTselikova**
https://github.com/malinink/easy-tests/issues/259
- [x] Refactor SolutionModelTest
- [x] Add AssertModelsListEquals and AssertEntitiesListEquals into SolutionsSupport
- [x] Refactor SolutionServiceTest

### CODE REVIEW

**Comment by malinink** [comment]
Add link to issue

**Comment by malinink** [comment]
@SvetlanaTselikova merge dev pls.

**Comment by SvetlanaTselikova** [comment]
@malinink Please,look

**Comment by malinink** [comment]
@SvetlanaTselikova GJ!

**Pull request merged**
