### PR TITLE
Refactor PointModelTest and PointServiceTest

### PR DESCRIPTION
**Pull request by SakhPrace**
#274 
- [X] Refactoring PointServiceTest
- [X] Refactoring PointModelTest

### CODE REVIEW

**Comment by SakhPrace** [comment]
@malinink check this PR please

**Comment by malinink** [comment]
@SakhPrace A lot of strange code, why not to copy original subject tests code?

**Comment by malinink** [comment]
@SakhPrace I'll do it by myself.

**Comment by malinink** [comment]
@AnyaMaz @SakhPrace pls look at hat https://github.com/malinink/easy-tests/commit/77a77c917d5c1b49feef5ce0327d6495d3f25469 https://github.com/malinink/easy-tests/commit/4743cf5320dbba01bdb3e5895dfe8f4848b02948 https://github.com/malinink/easy-tests/commit/16530e86f9021d6ea67c9f1284150aa2f1268543

**Pull request merged**
